---
- hosts: localhost
  connection: local
  collections:
    - infoblox.universal_ddi

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    # Delete the Host
    - name: Delete Host
      b1_ipam_host:
        name: "host"
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: absent
