---
- hosts: localhost
  connection: local
  collections:
    - infoblox.universal_ddi

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    #  Gather Host
    - name: Gather Host
      b1_ipam_host_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
      register: hostlists
    - name: printing hostlists
      debug: 
        msg: " {{ hostlists }} "
