---
- hosts: localhost
  connection: local
  collections:
    - blox.b1ddi

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    #  Gather all Subnet
    - name: Gather Subnet
      b1_ipam_subnet_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
      register: subnets
    - debug: msg="{{ subnets }}"