name: pr

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - run: |
          python -m pip install --upgrade pip
          pip install flynt lint black
          pip install -r requirements.txt

      - name: Run linters
        run: make lint

  pr-sanity-test:
    uses: ./.github/workflows/sanity.yml